title: Emil Varga
author:
  name: Emil Varga
  email: emil.varga (at) gmail.com
  github: cogitor
  twitter: emvar
  linkedin: emilvarga

url: https://emilvarga.com
image: https://emilvarga.com/assets/typing.jpg
permalink: /posts/:year/:month/:day/:title
production_url: https://emilvarga.com
markdown: kramdown
excerpt_separator: <!--break-->

defaults:
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

redirect_from:
  json: false