title: Software Engineering Musings
author:
  name: Emil Varga
  email: emil.varga (at) gmail.com
  github: cogitor
  twitter: emvar
  linkedin: emilvarga

permalink: /blog/:year/:month/:day/:title
production_url: http://emilvarga.com

markdown: redcarpet
redcarpet:
  extensions: []

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
