title: Emil Varga
author:
  name: Emil Varga
  email: emil.varga (at) gmail.com
  github: cogitor
  twitter: emvar
  linkedin: emilvarga

image: http://emilvarga.com/assets/typing.jpg
permalink: /posts/:year/:month/:day/:title
production_url: http://emilvarga.com
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
